FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ libc6-compat

COPY package*.json ./
RUN npm install

EXPOSE 3000

CMD ["sh", "-c", "npx prisma generate && npx prisma db push && npm run dev -- --hostname 0.0.0.0"]
